language: java
jdk:
  # TODO: Investigate why this is failing - oraclejdk8
  - oraclejdk7
  - openjdk7
branches:
  only:
  - master

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - mvn test cobertura:cobertura coveralls:report
