language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  - java_version=1.7
  - java_version=1.8

matrix:
  exclude:
    - jdk: oraclejdk8
      env: java_version=1.7
    - jdk: oraclejdk7
      env: java_version=1.8
    - jdk: openjdk7
      env: java_version=1.8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - mvn test cobertura:cobertura coveralls:report
