server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
#  requestLog:
#    timeZone: America/Los_Angeles
#    appenders: []

#server:
#  type: simple
#  applicationContextPath: /graphdemo

logging:
  level: INFO
#  loggers:
#    "http.request": OFF

applicationContextPath: scigraph

#apiConfiguration:
#  apikeyParameter: apikey
#  defaultApikey: default
#  authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
#  authenticationQuery: select APIKEY from USERS where APIKEY = ?
#  roleQuery: select ROLES from USERS where APIKEY = ?
##  permissionQuery: select PERMISSION from ROLES where ROLE = ?
#  authDataSourceFactory:
#    # the name of your JDBC driver
#    driverClass: org.hsqldb.jdbc.JDBCDriver

    # the username
#    user: SA

    # the password
#    password: password

    # the JDBC URL
#    url: jdbc:hsqldb:res:/users/users

    # any properties specific to your JDBC driver:
#    properties:
#      charSet: UTF-8

    # the maximum amount of time to wait on an empty pool before throwing an exception
#    maxWaitForConnection: 1s

    # the SQL query to run when validating a connection's liveness
#    validationQuery: "/* MyService Health Check */ SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"

    # the minimum number of connections to keep open
#    minSize: 8

    # the maximum number of connections to keep open
#    maxSize: 32

    # whether or not idle connections should be validated
#    checkConnectionWhileIdle: false

graphConfiguration:
  graphLocation: /temp/monarchGraph
