server:
  type: simple
  applicationContextPath: /scigraph
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
#  requestLog:
#    timeZone: America/Los_Angeles
#    appenders: []

#server:
#  type: simple
#  applicationContextPath: /graphdemo

logging:
  level: INFO
#  loggers:
#    "http.request": ON

applicationContextPath: scigraph

#apiConfiguration:
#  apikeyParameter: apikey
#  defaultApikey: default
#  authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
#  authenticationQuery: select APIKEY from USERS where APIKEY = ?
#  roleQuery: select ROLES from USERS where APIKEY = ?
##  permissionQuery: select PERMISSION from ROLES where ROLE = ?
#  authDataSourceFactory:
#    # the name of your JDBC driver
#    driverClass: org.hsqldb.jdbc.JDBCDriver

    # the username
#    user: SA

    # the password
#    password: password

    # the JDBC URL
#    url: jdbc:hsqldb:res:/users/users

    # any properties specific to your JDBC driver:
#    properties:
#      charSet: UTF-8

    # the maximum amount of time to wait on an empty pool before throwing an exception
#    maxWaitForConnection: 1s

    # the SQL query to run when validating a connection's liveness
#    validationQuery: "/* MyService Health Check */ SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"

    # the minimum number of connections to keep open
#    minSize: 8

    # the maximum number of connections to keep open
#    maxSize: 32

    # whether or not idle connections should be validated
#    checkConnectionWhileIdle: false

graphConfiguration:
  graphLocation: /temp/rosieGraph
  curies:
    http://purl.obolibrary.org/obo/DOID_ : DOID
    http://purl.obolibrary.org/obo/ORPHANET_ : ORPHANET
    http://purl.obolibrary.org/obo/OMIM_ : OMIM
    http://www.ncbi.nlm.nih.gov/pubmed/ : PMID
    http://purl.obolibrary.org/obo/HP_ : HP
    http://purl.obolibrary.org/obo/MP_ : MP
    http://purl.obolibrary.org/obo/ZP_ : ZP
    http://purl.obolibrary.org/obo/GENO_ : GENO
    http://purl.obolibrary.org/obo/ECO_ : ECO
    http://purl.obolibrary.org/obo/RO_ : RO
    http://purl.obolibrary.org/obo/BFO_ : BFO
#    http://monarch-initiative.org/data/MGI_ : MGI
    http://semanticscience.org/resource/SIO_ : SIO
    http://purl.obolibrary.org/obo/Ensembl_ : ENSEMBL
    http://purl.obolibrary.org/obo/ENSEMBL_ : ENSEMBL
#    http://purl.obolibrary.org/obo/MGI_ : MGI
    http://purl.obolibrary.org/obo/ZFIN_ : ZFIN
    http://purl.obolibrary.org/obo/UniProtKB_ : UNIPROT
    http://purl.obolibrary.org/obo/MESH_ : MESH
    http://purl.obolibrary.org/obo/MeSH_ : MESH
    http://purl.obolibrary.org/obo/UMLS_ : UMLS
    http://purl.obolibrary.org/obo/UMLS_CUI : UMLS
    http://purl.obolibrary.org/obo/WB_ : WB
    http://purl.obolibrary.org/obo/WormBase_ : WB
    http://purl.obolibrary.org/obo/FB_ : FB
    http://purl.obolibrary.org/obo/FlyBase_ : FB
    http://purl.obolibrary.org/obo/RGD_ : RGD
    http://purl.obolibrary.org/obo/MONARCH_ : MONARCH
    http://omia.angis.org.au/OMIA : OMIA
    http://purl.obolibrary.org/obo/OMIABreed_ : OMIABreed
    http://purl.obolibrary.org/obo/OMIAPub_ : OMIAPub

cypherResources:
  - path: /dynamic/genes_with_phenotype
    query: |
            START phenotype = node:node_auto_index(fragment={phenotype_id})
            MATCH (g:gene)-[r:RO_0002200*]->(phenotype)
            RETURN distinct g, r, phenotype
    operations:
      - nickname: genes_with_phenotype
        summary: Get genes related to a phenotype
        parameters:
          - name: phenotype_id
            description: The ID of the phenotype
            required: true
            type: string
            paramType: query
  - path: /dynamic/phenotypes_with_gene
    query: |
            START gene = node:node_auto_index(fragment={gene_id})
            MATCH (gene)-[r:RO_0002200*]->(phenotype:Phenotype)
            RETURN distinct gene, r, phenotype
    operations:
      - nickname: genes_with_phenotype
        summary: Get genes related to a phenotype
        parameters:
          - name: gene_id
            description: The ID of the gene
            required: true
            type: string
            paramType: query
  - path: /dynamic/genotypes_from_gene
    query: |
            START genotypeClass = node:node_auto_index(fragment='GENO_0000000'),
                  gene = node:node_auto_index(fragment={gene_id})
                  MATCH (gene)<-[geno:GENO_0000408]-(variantLocus)<-[part:BFO_0000051!*]-(genotype)-[:type]->(genotypeClass)
                  RETURN distinct gene, geno, variantLocus, part, genotype
    operations:
      - nickname: genotypes_from_gene
        summary: Get genotypes for a gene
        parameters:
          - name: gene_id
            description: The ID of the gene
            required: true
            type: string
            paramType: query
  - path: /dynamic/phenotypes_from_disease
    query: |
            START disease = node:node_auto_index(fragment={disease_id})
            MATCH (disease)<-[s1:subClassOf*0..]-(d)-[r:RO_0002200]->(p)-[s2:subClassOf*1..]->(phenotype:Phenotype)
            RETURN distinct disease, s1, d, r, p, s2, phenotype
    operations:
      - nickname: phenotypes_from_disease
        summary: Get phenotype for a disease
        parameters:
          - name: disease_id
            description: The ID of the disease
            required: true
            type: string
            paramType: query
  - path: /dynamic/diseases_from_phenotype
    query: |
            START phenotype = node:node_auto_index(fragment={phenotype_id})
            MATCH (disease:disease)<-[s1:subClassOf*0..]-(d)-[r:RO_0002200]->(p)-[s2:subClassOf*0..]->(phenotype:Phenotype)
            RETURN distinct disease, s1, d, r, p, s2, phenotype
    operations:
      - nickname: diseases_from_phenotype
        summary: Get diseases for a phenotype
        parameters:
          - name: phenotype_id
            description: The ID of the phenotype
            required: true
            type: string
            paramType: query


serviceMetadata:
  name: 'SciGraph Reconciliation Service'
  identifierSpace: 'http://example.org'
  schemaSpace: 'http://example.org'
  view: {
    url: 'http://localhost:9000/scigraph/refine/view/{{id}}'
  }
  preview: {
    url: 'http://localhost:9000/scigraph/refine/preview/{{id}}',
    width: 400,
    height: 400
  }
